### ISSUE TITLE
Google sync not working?

### ISSUE THREAD

**Issue by axel9546** [lineageos4microg/lineageos4microg.github.io#113]
Hi there! When I go on "Accounts" -> "Google" -> "Sync Settings" there is no listed option to sync Calendar or Contacts.
Infact, contacts are not syncing.
How to fix?

**Comment by unlikelywicked** [comment]
Hi,

I would also like to know what's supposed to happen when you sign in in to your google account ? 
Apparently no apps have access to my contacts from gmail whether it's the call app, whatszpp or any other messaging app. 
I've tried to export the contacts from that phone to reimport them, still the same result. 

I had to export the contacts from a stock google phone to actually got my contact in the ?"right"? Format so that every app have access to my contacts. 

Apparently it did not sync all of my contact from google either because there is only 250 contacts listed in place of 2000 ( i mean before i've imported from the google stock phone... 
Here is an answer feom.someone who had the same problem on reddit who was kind enough to answer me. 
https://www.reddit.com/r/MicroG/comments/122h5hj/problem_with_contacts_availability_to_all_apps/

So could have some clarifications about all that ? Or even a wiki page about it ?
