### ISSUE TITLE
Outdated information regarding signature spoofing

### ISSUE THREAD

**Issue by steffenWi** [lineageos4microg/lineageos4microg.github.io#130]
Hi,

the website still says 

> Why do we need a custom build of LineageOS to have microG? Can't I install microG on the official LineageOS?
> MicroG requires a patch called "signature spoofing", which allows the microG's apps to spoof themselves as Google Apps. 
> LineageOS' developers [refused](https://review.lineageos.org/#/c/64967/) ([multiple](https://review.lineageos.org/#/c/65366/) 
> [times](https://review.lineageos.org/#/c/195283/)) to include the patch, forcing us to fork their project.

but LineageOS has introduced signature spoofing for LineageOS 18.1 through 21.1 [source](https://review.lineageos.org/q/topic:microg-eval)

It'd be good to update the information on the website, specifically on whether Lineage4MicroG plans to continue providing builds and if not, how to switch over to LineageOS and how to install microG to gain the same result as if using Lineage4MicroG.

**Comment by petefoth** [comment]
> but LineageOS has introduced signature spoofing for LineageOS 18.1 through 21.1 [source](https://review.lineageos.org/q/topic:microg-eval)

They have introduced ***support*** for microG (i.e. their code no longer ***prevents*** the installation of microG), but thier builds do not include either  the microG components or the F-Droid app, with the microG repository configured and enabled. This project will continue to  make builds which ***do*** include those components, so that they will work 'out of the box'

 > It'd be good to update the information on the website, specifically on whether Lineage4MicroG plans to continue providing builds

This will be done as part of [Update and simplify web site #139 ](#139)

**Comment by petefoth** [comment]
> Hi, for those others reading this issue: The link in the last comment still leads to this issue.
> 
> This is the correct link: [#139](https://github.com/lineageos4microg/lineageos4microg.github.io/issues/139)

Thanks - link updated

**Comment by ChrLau** [comment]
Wow, that was fast. 😄
