### ISSUE TITLE
mention an alternative to "heimdall"

### ISSUE THREAD

**Issue by herrdeh** [lineageos4microg/lineageos4microg.github.io#84]
On a Samsung A3 (2016) I could not make "heimdall" flash the recovery. As that seems to be quite a common problem, it would be a good thing to mention alternatives - especially for Linux and MacOS. 

Besides that, install instructions for heimdall seem to be a little outdated: On the link provided you get two files now, one is called "heimdall-frontend". The page does not give info if you can work with it and how.

These are my error messages:
```
ERROR: Failed to receive file part response!

ERROR: Retrying...
ERROR: Expected file part index: 0 Received: 1
ERROR: RECOVERY upload failed!
```

**Comment by amo13** [comment]
Heimdall in general is kind of outdated and an abandoned project. Still, pull requests to the original repository are flowing in, but unfortunately, they won't get merged there, because the original author and maintainer of the repo has no time or does not care? I created [a fork](https://github.com/amo13/Heimdall) with some crucial pull requests merged. I can't promise that it is also going to work for the A3, but you might want to try it.
Unfortunately, there is no established alternative yet. The only projects I know of are very young: [Hreidmar](https://github.com/Samsung-Loki/Hreidmar) and [wuotan](https://github.com/nickelc/wuotan).

**Comment by petefoth** [comment]
Our [instructions for installng our ROMs](https://github.com/lineageos4microg/docker-lineage-cicd#how-do-i-install-the-lineageos-for-microg-rom) are 
> Follow the LineageOS installation instructions for your device, which can be accessed from the [LineageOS Devices wiki pages](https://wiki.lineageos.org/devices/).

If those instructions are unclear, then you should take it up with the LineageOS project.

Closing this issue as there is nothing we can do
